"""create user table

Revision ID: 705605dac87a
Revises: 
Create Date: 2022-12-22 21:08:53.639361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "705605dac87a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), server_default="", nullable=False),
        sa.Column("username", sa.String(length=30), server_default="", nullable=False),
        sa.Column("email", sa.String(length=40), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
